---
- hosts: server2.abc.com
  user: sravan
  sudo: yes
  connection: ssh
  tasks:
      - name: installing httpd package
        yum : name=httpd state=installed
      - name: copying index.html file
        copy: src=index.html dest=/var/www/html
      - name: starting httpd service
        service: name=httpd state=started 

